# Generated by Django 5.1.4 on 2025-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rgpd_consent',
            new_name='can_be_contacted',
        ),
        migrations.AddField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=True),
        ),
    ]
